### ISSUE TITLE
Add i18n for the button labels

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin-component-factory/multi-combo-box-flow#11]
Add i18n for the button labels

**Comment by mheicke** [comment]
Alternative add a function `buttonLabelProvider(Function<ButtonType, String> provider)` with enum for the button type (SELECT_ALL, CLEAR)

**Comment by jcgueriaud1** [comment]
Released in https://github.com/vaadin-component-factory/multi-combo-box-flow/releases/tag/v0.3.0

Here is a example: https://github.com/vaadin-component-factory/multi-combo-box-flow/blob/main/multi-combo-box-flow-demo/src/main/java/com/vaadin/componentfactory/multiselect/I18nView.java#L23
